version: "3.9"
services:
  web:
    build: . 
    ports:
      - "8000:8080"
    depends_on:
      - db
    restart: always
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test-db
    ports:
      - "5432:5432"